version: '3'

services:
  django:
    build:
      context: ./config
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
#   command: gunicorn --env DJANGO_SETTINGS_MODULE=config.settings.production --bind 127.0.0.1:8000 config.wsgi:application

    volumes:
      - static_volume:/usr/src/app/statics
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/statics
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: