version: '3'

services:
  django:
    build:
      context: ./config
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:11.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.db

  nginx:
    build: ./nginx
    volumes:
      - ./frontend/dist:/var/www
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django


volumes:
  postgres_data:
  static_volume: