# Generated by Django 3.1.2 on 2020-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
