# Generated by Django 3.1.2 on 2020-10-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intro',
        ),
    ]
