# Generated by Django 3.1.2 on 2020-10-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201021_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='profile',
        ),
    ]
