# Generated by Django 3.1.2 on 2020-11-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(default=1, max_length=20, verbose_name='駐車場'),
            preserve_default=False,
        ),
    ]
