# Generated by Django 3.1.2 on 2020-10-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201020_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo/', verbose_name='サムネイル画像'),
            preserve_default=False,
        ),
    ]
