# Generated by Django 3.1.2 on 2020-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='point',
        ),
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.IntegerField(choices=[(1, '★1'), (2, '★2'), (3, '★3'), (4, '★4'), (5, '★5')], default=3, verbose_name='評価点'),
        ),
    ]
