# Generated by Django 3.1.2 on 2020-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201024_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo/', verbose_name='サムネイル画像'),
            preserve_default=False,
        ),
    ]
