# Generated by Django 3.1.2 on 2020-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car_type',
            field=models.CharField(choices=[('Corolla', 'Corolla'), ('Prius', 'Prius'), ('Voxy', 'Voxy')], max_length=20),
        ),
    ]
