# Generated by Django 3.1.2 on 2020-10-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201025_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car_type',
            field=models.CharField(choices=[('corolla', 'Corolla'), ('prius', 'Prius'), ('voxy', 'Voxy')], max_length=20),
        ),
    ]
