# Generated by Django 3.1.2 on 2020-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201025_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='car_type',
            field=models.CharField(choices=[('corolla', 'corolla'), ('prius', 'prius'), ('voxy', 'voxy')], max_length=20),
        ),
    ]
