# Generated by Django 3.1.2 on 2020-10-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201025_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pr1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='おすすめ1'),
        ),
        migrations.AddField(
            model_name='post',
            name='pr2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='おすすめ2'),
        ),
        migrations.AddField(
            model_name='post',
            name='pr3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='おすすめ3'),
        ),
        migrations.AddField(
            model_name='post',
            name='pr4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='おすすめ4'),
        ),
    ]
