# Generated by Django 3.1.2 on 2020-10-17 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
